// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhmjfzdqjtptrjhbficz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobWpmemRxanRwdHJqaGJmaWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDA5NjYsImV4cCI6MjA2NDAxNjk2Nn0.A-9BvM3aBZmtLA4xHYlcTdJ4Jtx4EpmDPdnT9UkRR9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);